export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_CHANGE_PASSWORD = "USER_CHANGE_PASSWORD"

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SYSTEM_ERROR = "AUTH_SYSTEM_ERROR";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";


export const CART_SUCCESS = 'CART_SUCCESS'
export const CART_FAILED = 'CART_FAILED'
export const CART_LOADING = 'CART_LOADING'

export const DELETE_CART_SUCCESS = 'DELETE_CART'
export const DELETE_CART_FAILED = 'DELETE_CART_FAILED'
export const DELETE_CART_LOADING = 'DELETE_CART_LOADING'

export const NOTIFICATION = 'NOTIFICATION'